// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twoint-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TwoInt struct {
	A                    uint64   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    uint64   `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoInt) Reset()         { *m = TwoInt{} }
func (m *TwoInt) String() string { return proto.CompactTextString(m) }
func (*TwoInt) ProtoMessage()    {}
func (*TwoInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f42938a99305543, []int{0}
}

func (m *TwoInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoInt.Unmarshal(m, b)
}
func (m *TwoInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoInt.Marshal(b, m, deterministic)
}
func (m *TwoInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoInt.Merge(m, src)
}
func (m *TwoInt) XXX_Size() int {
	return xxx_messageInfo_TwoInt.Size(m)
}
func (m *TwoInt) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoInt.DiscardUnknown(m)
}

var xxx_messageInfo_TwoInt proto.InternalMessageInfo

func (m *TwoInt) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *TwoInt) GetB() uint64 {
	if m != nil {
		return m.B
	}
	return 0
}

type AddRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	TwoInt               *TwoInt  `protobuf:"bytes,2,opt,name=twoInt,proto3" json:"twoInt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f42938a99305543, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *AddRequest) GetTwoInt() *TwoInt {
	if m != nil {
		return m.TwoInt
	}
	return nil
}

type AddResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Result               uint64   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f42938a99305543, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *AddResponse) GetResult() uint64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*TwoInt)(nil), "v1.TwoInt")
	proto.RegisterType((*AddRequest)(nil), "v1.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "v1.AddResponse")
}

func init() {
	proto.RegisterFile("twoint-service.proto", fileDescriptor_1f42938a99305543)
}

var fileDescriptor_1f42938a99305543 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x29, 0xcf, 0xcf,
	0xcc, 0x2b, 0xd1, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x33, 0x54, 0x52, 0xe1, 0x62, 0x0b, 0x29, 0xcf, 0xf7, 0xcc, 0x2b, 0x11, 0xe2,
	0xe1, 0x62, 0x4c, 0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x62, 0x4c, 0x04, 0xf1, 0x92, 0x24,
	0x98, 0x20, 0xbc, 0x24, 0x25, 0x27, 0x2e, 0x2e, 0xc7, 0x94, 0x94, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x01, 0x2e, 0xe6, 0xc4, 0x82, 0x4c, 0xb0, 0x5a, 0xce, 0x20, 0x10, 0x53, 0x48,
	0x89, 0x8b, 0xad, 0x04, 0x6c, 0x0a, 0x58, 0x0b, 0xb7, 0x11, 0x97, 0x5e, 0x99, 0xa1, 0x1e, 0xc4,
	0xdc, 0x20, 0xa8, 0x8c, 0x92, 0x39, 0x17, 0x37, 0xd8, 0x8c, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54,
	0x2c, 0x86, 0x88, 0x71, 0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x40, 0xed, 0x85, 0xf2, 0x8c,
	0xcc, 0xb9, 0x78, 0x21, 0x46, 0x05, 0x43, 0x5c, 0x2f, 0xa4, 0xc6, 0xc5, 0xec, 0x98, 0x92, 0x22,
	0xc4, 0x07, 0xb2, 0x04, 0xe1, 0x2c, 0x29, 0x7e, 0x38, 0x1f, 0x62, 0x45, 0x12, 0x1b, 0xd8, 0x9b,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87, 0x16, 0x4d, 0xf0, 0xfe, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TwoIntServiceClient is the client API for TwoIntService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TwoIntServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type twoIntServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTwoIntServiceClient(cc grpc.ClientConnInterface) TwoIntServiceClient {
	return &twoIntServiceClient{cc}
}

func (c *twoIntServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/v1.TwoIntService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwoIntServiceServer is the server API for TwoIntService service.
type TwoIntServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

// UnimplementedTwoIntServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTwoIntServiceServer struct {
}

func (*UnimplementedTwoIntServiceServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterTwoIntServiceServer(s *grpc.Server, srv TwoIntServiceServer) {
	s.RegisterService(&_TwoIntService_serviceDesc, srv)
}

func _TwoIntService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwoIntServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TwoIntService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwoIntServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TwoIntService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TwoIntService",
	HandlerType: (*TwoIntServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TwoIntService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twoint-service.proto",
}
